name: Deploy-Docs
permissions:         # <-- add
  contents: write    # allow push back to repo
on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'research/**'
      - 'mkdocs.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force   # publishes to gh-pages
