name: Deploy-Docs
permissions:
  contents: write      # needed for gh-pages push

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'research/**'
      - 'mkdocs.yml'
  workflow_dispatch:

jobs:
  build:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MkDocs
        run: pip install mkdocs-material

      - name: Build & deploy to gh-pages
        run: mkdocs gh-deploy --force --remote-branch gh-pages
